"""Canonical source registry for the dashboard.

This file is the guardrail layer.  It deliberately sits beside the existing
provider flow so source credibility rules can be audited without a large
runtime refactor.
"""

from __future__ import annotations

from copy import deepcopy


TRUST_LEVELS = {"官方", "官方延迟", "第三方", "备用源", "代理", "同源"}
REQUIRED_FIELDS = {
    "symbol",
    "display_name",
    "asset_type",
    "snapshot_source",
    "history_source",
    "valuation_source",
    "fallback_source",
    "trust_label",
    "update_label",
    "supports_chart",
    "supports_total_return",
    "price_index_code",
    "total_return_index_code",
    "allowed_periods",
    "source_url",
    "notes",
}


PERIODS_ALL = ["1mo", "3mo", "6mo", "1y", "3y", "5y", "10y", "all"]
PERIODS_DAX = ["1mo", "3mo"]


SOURCE_REGISTRY = {
    "CSI300": {
        "symbol": "CSI300",
        "display_name": "沪深300",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_official",
        "history_source": "tx",
        "valuation_source": "csindex_pe",
        "fallback_source": "sina",
        "trust_label": "官方",
        "update_label": "实时",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "000300",
        "total_return_index_code": "H00300",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=000300",
        "notes": "卡片使用中证指数官网日内快照；价格历史使用免费第三方日线，全收益为中证官方代码。",
    },
    "CSI500": {
        "symbol": "CSI500",
        "display_name": "中证A500",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_official",
        "history_source": "tx",
        "valuation_source": "csindex_pe",
        "fallback_source": "sina",
        "trust_label": "官方",
        "update_label": "实时",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "000510",
        "total_return_index_code": "000510CNY010",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=000510",
        "notes": "卡片使用中证指数官网日内快照；价格历史使用免费第三方日线，全收益为中证官方代码。",
    },
    "CSI500_INDEX": {
        "symbol": "CSI500_INDEX",
        "display_name": "中证500",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_official",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "sina",
        "trust_label": "官方",
        "update_label": "实时",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "000905",
        "total_return_index_code": "H00905",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=000905",
        "notes": "中证500价格指数000905，全收益指数H00905；卡片和历史优先使用中证指数官网官方数据。",
    },
    "CSI_DIVIDEND": {
        "symbol": "CSI_DIVIDEND",
        "display_name": "中证红利低波动",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_perf_snapshot",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "H30269",
        "total_return_index_code": "H20269",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=H30269",
        "notes": "价格指数 H30269，全收益指数 H20269；禁止 ETF/代理污染。",
    },
    "CSI_DIVIDEND_100": {
        "symbol": "CSI_DIVIDEND_100",
        "display_name": "中证红利低波100",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_perf_snapshot",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "930955",
        "total_return_index_code": "H20955",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=930955",
        "notes": "价格指数 930955，全收益指数 H20955；禁止 ETF/代理污染。",
    },
    "CSI300_DIVIDEND_LOW_VOL": {
        "symbol": "CSI300_DIVIDEND_LOW_VOL",
        "display_name": "沪深300红利低波",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_perf_snapshot",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "930740",
        "total_return_index_code": "H20740",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=930740",
        "notes": "价格指数 930740，全收益指数 H20740；禁止 ETF/代理污染。",
    },
    "CSI_DIVIDEND_QUALITY": {
        "symbol": "CSI_DIVIDEND_QUALITY",
        "display_name": "红利质量",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_perf_snapshot",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "931468",
        "total_return_index_code": "921468",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=931468",
        "notes": "价格指数 931468，全收益指数 921468；中证官方日线与官方 PE。",
    },
    "CSI_ALL_DIVIDEND_QUALITY": {
        "symbol": "CSI_ALL_DIVIDEND_QUALITY",
        "display_name": "中证红利质量",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_perf_snapshot",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "932315",
        "total_return_index_code": "932315CNY010",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=932315",
        "notes": "价格指数 932315，全收益指数 932315CNY010；中证官方日线与官方 PE。",
    },
    "CSI_CASH_FLOW": {
        "symbol": "CSI_CASH_FLOW",
        "display_name": "中证现金流",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_perf_snapshot",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "932365",
        "total_return_index_code": "932365CNY010",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=932365",
        "notes": "价格指数 932365，全收益指数 932365CNY010；中证官方日线与官方 PE。",
    },
    "CNI_FREE_CASH_FLOW": {
        "symbol": "CNI_FREE_CASH_FLOW",
        "display_name": "国证自由现金流",
        "asset_type": "cn_index",
        "snapshot_source": "cni_official",
        "history_source": "cni_official",
        "valuation_source": "none",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "980092",
        "total_return_index_code": "480092",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.cnindex.com.cn/module/index-detail.html?act_menu=1&indexCode=980092",
        "notes": "价格指数 980092，收益指数 480092；来自国证指数网公开日线。",
    },
    "CSI_BAIJIU": {
        "symbol": "CSI_BAIJIU",
        "display_name": "中证白酒指数",
        "asset_type": "cn_index",
        "snapshot_source": "sina",
        "history_source": "tx",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "第三方",
        "update_label": "实时",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "399997",
        "total_return_index_code": "H20539",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://finance.sina.com.cn/stock/stockindex/",
        "notes": "免费第三方快照；全收益为中证官方代码。",
    },
    "CHINEXT": {
        "symbol": "CHINEXT",
        "display_name": "创业板指",
        "asset_type": "cn_index",
        "snapshot_source": "sina",
        "history_source": "tx",
        "valuation_source": "price_percentile",
        "fallback_source": "eastmoney_quote",
        "trust_label": "第三方",
        "update_label": "实时",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "399006",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://finance.sina.com.cn/stock/stockindex/",
        "notes": "免费第三方快照和历史；不启用 total_return，避免非官方直连源误标。",
    },
    "STAR50": {
        "symbol": "STAR50",
        "display_name": "科创50",
        "asset_type": "cn_index",
        "snapshot_source": "sina",
        "history_source": "tx",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "第三方",
        "update_label": "实时",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "000688",
        "total_return_index_code": "000688CNY01",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://finance.sina.com.cn/stock/stockindex/",
        "notes": "免费第三方快照；全收益和 PE 优先使用中证官方序列。",
    },
    "STAR100": {
        "symbol": "STAR100",
        "display_name": "科创100",
        "asset_type": "cn_index",
        "snapshot_source": "sina",
        "history_source": "tx",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "第三方",
        "update_label": "实时",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "000698",
        "total_return_index_code": "000698CNY010",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://finance.sina.com.cn/stock/stockindex/",
        "notes": "免费第三方快照；全收益和 PE 优先使用中证官方序列。",
    },
    "CN10Y": {
        "symbol": "CN10Y",
        "display_name": "中国国债十年收益率",
        "asset_type": "bond_yield",
        "snapshot_source": "chinabond",
        "history_source": "chinabond",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "CN10Y",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://yield.chinabond.com.cn/",
        "notes": "官方收益率曲线；ETF代理收益只可标为代理，不可作为官方 total_return。",
    },
    "US10Y": {
        "symbol": "US10Y",
        "display_name": "美国国债十年收益率",
        "asset_type": "bond_yield",
        "snapshot_source": "us_treasury",
        "history_source": "us_treasury",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "US10Y",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://home.treasury.gov/resource-center/data-chart-center/interest-rates",
        "notes": "官方收益率曲线；ETF代理收益只可标为代理，不可作为官方 total_return。",
    },
    "HSTECH": {
        "symbol": "HSTECH",
        "display_name": "恒生科技指数",
        "asset_type": "hk_index",
        "snapshot_source": "sina",
        "history_source": "hk_sina",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "第三方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "HSTECH",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://finance.sina.com.cn/stock/hkstock/",
        "notes": "免费第三方快照；3033.HK 只能作为 ETF代理收益。",
    },
    "HSI": {
        "symbol": "HSI",
        "display_name": "恒生指数",
        "asset_type": "hk_index",
        "snapshot_source": "hsi_daily_bulletin",
        "history_source": "hk_sina",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "HSI",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.hsi.com.hk/",
        "notes": "卡片使用恒生指数公司日更报表；2800.HK 只能作为 ETF代理收益。",
    },
    "DAX": {
        "symbol": "DAX",
        "display_name": "德国DAX指数",
        "asset_type": "global_index",
        "snapshot_source": "deutsche_boerse",
        "history_source": "stoxx_dax",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "DAXK",
        "total_return_index_code": "DAX",
        "allowed_periods": PERIODS_DAX,
        "source_url": "https://live.deutsche-boerse.com/indices/dax",
        "notes": "STOXX公开3个月历史文件：DAXK为价格指数，DAX headline为performance/total-return口径；免费稳定历史只开放短周期。",
    },
    "NDX": {
        "symbol": "NDX",
        "display_name": "纳斯达克100",
        "asset_type": "us_index",
        "snapshot_source": "nasdaq_official",
        "history_source": "yahoo_chart",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "官方延迟",
        "update_label": "延迟",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "^NDX",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://indexes.nasdaq.com/Index/Overview/NDX",
        "notes": "官方延迟快照；QQQ 只能作为 ETF代理收益。",
    },
    "SPX": {
        "symbol": "SPX",
        "display_name": "标普500",
        "asset_type": "us_index",
        "snapshot_source": "sina",
        "history_source": "yahoo_chart",
        "valuation_source": "multpl_pe",
        "fallback_source": "",
        "trust_label": "第三方",
        "update_label": "延迟",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "^GSPC",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://finance.sina.com.cn/stock/usstock/",
        "notes": "免费第三方快照；PE 为 multpl 月度 TTM 估值参考；不启用 total_return，避免非官方直连源误标。",
    },
    "XOP": {
        "symbol": "XOP",
        "display_name": "标普油气ETF",
        "asset_type": "etf",
        "snapshot_source": "sina",
        "history_source": "yahoo_chart",
        "valuation_source": "",
        "fallback_source": "",
        "trust_label": "第三方",
        "update_label": "延迟",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "XOP",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://finance.sina.com.cn/stock/usstock/",
        "notes": "ETF 本体，不显示股票指数 PE；复权收益只能标复权。",
    },
    "WANJIA_GOLD": {
        "symbol": "WANJIA_GOLD",
        "display_name": "万家周期视野C",
        "asset_type": "fund",
        "snapshot_source": "fund_nav",
        "history_source": "fund_nav",
        "valuation_source": "",
        "fallback_source": "",
        "trust_label": "第三方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "025446",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://fund.eastmoney.com/025446.html",
        "notes": "基金净值，不显示指数 PE。",
    },
    "GOLD": {
        "symbol": "GOLD",
        "display_name": "黄金",
        "asset_type": "commodity",
        "snapshot_source": "sina",
        "history_source": "yahoo_chart",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "第三方",
        "update_label": "延迟",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "GC=F",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://finance.sina.com.cn/futures/quotes/GC.shtml",
        "notes": "免费延迟商品期货快照；同源价格线不是全收益。",
    },
    "OIL_WTI": {
        "symbol": "OIL_WTI",
        "display_name": "WTI原油",
        "asset_type": "commodity",
        "snapshot_source": "sina",
        "history_source": "yahoo_chart",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "第三方",
        "update_label": "延迟",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "CL=F",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://finance.sina.com.cn/futures/quotes/CL.shtml",
        "notes": "免费延迟商品期货快照；同源价格线不是全收益。",
    },
    "CSI_ALL_SHARE": {
        "symbol": "CSI_ALL_SHARE",
        "display_name": "中证全指",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_perf_snapshot",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "000985",
        "total_return_index_code": "H00985",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=000985",
        "notes": "价格指数000985，全收益指数H00985；使用中证指数官网官方日线。",
    },
    "CSI1000": {
        "symbol": "CSI1000",
        "display_name": "中证1000",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_perf_snapshot",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "000852",
        "total_return_index_code": "H00852",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=000852",
        "notes": "价格指数000852，全收益指数H00852；使用中证指数官网官方日线。",
    },
    "CSI2000": {
        "symbol": "CSI2000",
        "display_name": "中证2000",
        "asset_type": "cn_index",
        "snapshot_source": "csindex_perf_snapshot",
        "history_source": "csindex_perf",
        "valuation_source": "csindex_pe",
        "fallback_source": "eastmoney_quote",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": "932000",
        "total_return_index_code": "932000CNY010",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.csindex.com.cn/#/indices/family/detail?indexCode=932000",
        "notes": "价格指数932000，全收益指数932000CNY010；使用中证指数官网官方日线。",
    },
    "EU10Y": {
        "symbol": "EU10Y",
        "display_name": "欧元区10年AAA收益率",
        "asset_type": "bond_yield",
        "snapshot_source": "ecb_yield",
        "history_source": "ecb_yield",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "YC.B.U2.EUR.4F.G_N_A.SV_C_YM.SR_10Y",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://data.ecb.europa.eu/",
        "notes": "European Central Bank欧元区AAA收益率曲线10年期序列。",
    },
    "VIX": {
        "symbol": "VIX",
        "display_name": "VIX恐慌指数",
        "asset_type": "risk_index",
        "snapshot_source": "cboe_vix",
        "history_source": "cboe_vix",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "官方",
        "update_label": "日更",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "VIX",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.cboe.com/tradable_products/vix/vix_historical_data/",
        "notes": "Cboe官方VIX历史数据。",
    },
    "USDCNY": {
        "symbol": "USDCNY",
        "display_name": "美元兑人民币",
        "asset_type": "fx",
        "snapshot_source": "usdcny",
        "history_source": "",
        "valuation_source": "",
        "fallback_source": "",
        "trust_label": "第三方",
        "update_label": "实时",
        "supports_chart": False,
        "supports_total_return": False,
        "price_index_code": "USDCNY",
        "total_return_index_code": "",
        "allowed_periods": ["1mo"],
        "source_url": "https://finance.sina.com.cn/money/forex/",
        "notes": "新浪财经免费外汇快照；不提供看板级历史曲线。",
    },
    "BTCUSD": {
        "symbol": "BTCUSD",
        "display_name": "比特币",
        "asset_type": "crypto",
        "snapshot_source": "coinbase",
        "history_source": "coinbase_candles",
        "valuation_source": "",
        "fallback_source": "",
        "trust_label": "官方",
        "update_label": "实时",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "BTC-USD",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://api.exchange.coinbase.com/products/BTC-USD",
        "notes": "Coinbase Exchange公开ticker与日线candles；不构造全收益线。",
    },
    "ETHUSD": {
        "symbol": "ETHUSD",
        "display_name": "以太币",
        "asset_type": "crypto",
        "snapshot_source": "coinbase",
        "history_source": "coinbase_candles",
        "valuation_source": "",
        "fallback_source": "",
        "trust_label": "官方",
        "update_label": "实时",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "ETH-USD",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://api.exchange.coinbase.com/products/ETH-USD",
        "notes": "Coinbase Exchange公开ticker与日线candles；不构造全收益线。",
    },
    "CAC40": {
        "symbol": "CAC40",
        "display_name": "法国CAC40",
        "asset_type": "global_index",
        "snapshot_source": "history_snapshot",
        "history_source": "yahoo_chart",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "第三方",
        "update_label": "延迟",
        "supports_chart": True,
        "supports_total_return": False,
        "price_index_code": "^FCHI",
        "total_return_index_code": "",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.euronext.com/en/products/indices/FR0003500008-XPAR",
        "notes": "免费延迟日线用于看板；官方Euronext页面作为口径参考。已测试CAC40 GR免费候选源：可复用长历史接口不稳定或仅返回单点/短窗口，因此不接入全收益曲线。",
    },
    "FTSE100": {
        "symbol": "FTSE100",
        "display_name": "英国富时100",
        "asset_type": "global_index",
        "snapshot_source": "history_snapshot",
        "history_source": "lse_dory",
        "valuation_source": "price_percentile",
        "fallback_source": "",
        "trust_label": "官方延迟",
        "update_label": "延迟",
        "supports_chart": True,
        "supports_total_return": True,
        "price_index_code": ".FTSE",
        "total_return_index_code": ".TRIUKX",
        "allowed_periods": PERIODS_ALL,
        "source_url": "https://www.londonstockexchange.com/indices/ftse-100",
        "notes": "LSE页面图表使用Refinitiv time-series接口；.FTSE为价格指数，.TRIUKX为FTSE100 Total Return。全收益历史从接口可得日期开始展示。",
    },
}


OFFICIAL_TOTAL_RETURN_CODES = {
    key: value["total_return_index_code"]
    for key, value in SOURCE_REGISTRY.items()
    if value.get("supports_total_return") and value.get("total_return_index_code")
}


def get_source_registry() -> dict[str, dict]:
    return deepcopy(SOURCE_REGISTRY)


def get_source_entry(symbol: str) -> dict | None:
    entry = SOURCE_REGISTRY.get(symbol)
    return deepcopy(entry) if entry else None


def validate_source_registry() -> list[str]:
    errors: list[str] = []
    for key, entry in SOURCE_REGISTRY.items():
        missing = sorted(REQUIRED_FIELDS - set(entry))
        if missing:
            errors.append(f"{key}: missing fields {', '.join(missing)}")
        if entry.get("symbol") != key:
            errors.append(f"{key}: symbol field must equal registry key")
        if entry.get("trust_label") not in TRUST_LEVELS:
            errors.append(f"{key}: invalid trust_label {entry.get('trust_label')!r}")
        if not isinstance(entry.get("allowed_periods"), list) or not entry.get("allowed_periods"):
            errors.append(f"{key}: allowed_periods must be a non-empty list")
        if entry.get("supports_total_return"):
            code = entry.get("total_return_index_code")
            if not code:
                errors.append(f"{key}: supports_total_return requires official total_return_index_code")
            if entry.get("trust_label") in {"代理", "同源"}:
                errors.append(f"{key}: official total_return cannot use proxy/same-source trust")
        elif entry.get("total_return_index_code"):
            errors.append(f"{key}: total_return_index_code present but supports_total_return is false")
    return errors


def print_registry_table() -> None:
    headers = [
        "symbol",
        "display_name",
        "trust_label",
        "update_label",
        "snapshot_source",
        "history_source",
        "valuation_source",
        "supports_total_return",
        "price_index_code",
        "total_return_index_code",
        "allowed_periods",
    ]
    print("\t".join(headers))
    for key in sorted(SOURCE_REGISTRY):
        row = SOURCE_REGISTRY[key]
        print("\t".join(str(row.get(header, "")) for header in headers))


if __name__ == "__main__":
    issues = validate_source_registry()
    print_registry_table()
    if issues:
        print("\nFAIL")
        for issue in issues:
            print(f"- {issue}")
        raise SystemExit(1)
    print("\nPASS")
